### ISSUE TITLE
Ruby solution idioms

### ISSUE THREAD

**Issue by MattMatero** [adelphimathcs/ProjectEuler-0010#1]
In the ruby Sieve method the for loop should be replaced by some other iterator, possibly .each or .reduce if necessary. Also I think the step method is more clear if used (i**2 .. upto).step(i) as ranges are more common in ruby than passing bounds as parameters.

**Comment by MichaelVessia** [comment]
My most recent commit is an attempt to follow more idiomatic ruby standards.  What do you think?

**Comment by MattMatero** [comment]
I think it's a bit more clear than what it was. I'm still not 100% sure on the best practice of using the 'next' keyword but I have no evidence to claim that it isn't idiomatic either.
